"""messages

Revision ID: 9464d18b3444
Revises: 9ae9749109e8
Create Date: 2023-03-03 10:59:55.072451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9464d18b3444'
down_revision = '9ae9749109e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Messages',
    sa.Column('MessageID', sa.Integer(), nullable=False),
    sa.Column('Namn', sa.String(length=100), nullable=False),
    sa.Column('Epost', sa.String(length=100), nullable=False),
    sa.Column('Telefon', sa.String(length=100), nullable=False),
    sa.Column('Rubrik', sa.String(length=100), nullable=False),
    sa.Column('Text', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('MessageID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Messages')
    # ### end Alembic commands ###
